INSERT OR IGNORE INTO english_kid_topic (code, parent_code, name, description, translations, position) VALUES
  ('about-me', NULL, 'About Me', 'The child''s body, feelings, clothes, and personal identity.', '{"vi":{"name":"Bản thân em","description":"Cơ thể, cảm xúc, quần áo và những điều cơ bản về bản thân."}}', 10),
  ('family-and-friends', NULL, 'Family and Friends', 'Family members, friends, and everyday relationships.', '{"vi":{"name":"Gia đình và bạn bè","description":"Các thành viên gia đình, bạn bè và những mối quan hệ gần gũi."}}', 20),
  ('home-and-daily-life', NULL, 'Home and Daily Life', 'Home, routines, and simple everyday responsibilities.', '{"vi":{"name":"Nhà cửa và sinh hoạt hằng ngày","description":"Ngôi nhà, thói quen và các việc hằng ngày đơn giản."}}', 30),
  ('school-and-learning', NULL, 'School and Learning', 'Classroom objects, school life, and early learning.', '{"vi":{"name":"Trường học và học tập","description":"Đồ dùng lớp học, đời sống ở trường và việc học cơ bản."}}', 40),
  ('food-and-drink', NULL, 'Food and Drink', 'Meals, food groups, snacks, and drinks.', '{"vi":{"name":"Đồ ăn và thức uống","description":"Bữa ăn, nhóm thực phẩm, đồ ăn nhẹ và thức uống."}}', 50),
  ('animals', NULL, 'Animals', 'Pets, farm animals, and familiar wild animals.', '{"vi":{"name":"Động vật","description":"Thú cưng, động vật trang trại và các động vật hoang dã quen thuộc."}}', 60),
  ('nature-and-weather', NULL, 'Nature and Weather', 'Weather, seasons, plants, and the natural world.', '{"vi":{"name":"Thiên nhiên và thời tiết","description":"Thời tiết, mùa, cây cối và thế giới tự nhiên."}}', 70),
  ('play-and-hobbies', NULL, 'Play and Hobbies', 'Toys, games, sports, and free-time activities.', '{"vi":{"name":"Vui chơi và sở thích","description":"Đồ chơi, trò chơi, thể thao và hoạt động lúc rảnh."}}', 80),
  ('travel-and-places', NULL, 'Travel and Places', 'Transport and familiar places in the community.', '{"vi":{"name":"Di chuyển và địa điểm","description":"Phương tiện đi lại và các địa điểm quen thuộc trong cộng đồng."}}', 90),
  ('people-and-community', NULL, 'People and Community', 'Jobs, community helpers, and caring for others.', '{"vi":{"name":"Con người và cộng đồng","description":"Nghề nghiệp, những người giúp đỡ cộng đồng và quan tâm người khác."}}', 100),
  ('early-concepts', NULL, 'Early Concepts', 'Numbers, colours, shapes, size, time, and basic comparisons.', '{"vi":{"name":"Khái niệm nền tảng","description":"Số đếm, màu sắc, hình khối, kích thước, thời gian và so sánh cơ bản."}}', 110),
  ('celebrations', NULL, 'Celebrations', 'Birthdays, holidays, and simple family traditions.', '{"vi":{"name":"Lễ kỷ niệm","description":"Sinh nhật, ngày lễ và các truyền thống gia đình đơn giản."}}', 120);
