-- =============================================================================
-- ENGLISH INSTRUCTIONS
--
-- A reusable catalog of short English instructions. It is intentionally not
-- tied to flashcards, so the same instruction can be used by any learning
-- activity without duplication.
--
-- `pronunciation` stores Kokoro replacement markup only when normal
-- text-to-speech is not sufficient; NULL means send `text` to Kokoro unchanged.
-- `translations` keeps localized learner-facing text by locale, for example
-- `{ "vi": { "text": "Chọn đáp án đúng." } }`.
-- `audio` is the final public URL after generated audio has been uploaded to
-- R2. Audio is always stored at
-- `instructions/{id}/{voice_id}.opus`, so regenerating the same
-- instruction and voice replaces the old object instead of leaving R2 garbage.
--
-- IDs are UUIDv7 generated by the API. No lifecycle metadata, ordering, or
-- activity-specific relation is stored here.
-- =============================================================================

CREATE TABLE english_instructions (
  id TEXT PRIMARY KEY NOT NULL CHECK (length(trim(id)) > 0),
  text TEXT NOT NULL CHECK (length(trim(text)) > 0),
  translations TEXT NOT NULL DEFAULT '{}' CHECK (
    json_valid(translations) AND json_type(translations) = 'object'
  ),
  pronunciation TEXT,
  voice_id TEXT NOT NULL DEFAULT 'kokoro-af_heart',
  audio TEXT,
  CONSTRAINT uq_english_instruction_text_voice UNIQUE (text COLLATE NOCASE, voice_id)
);

CREATE INDEX idx_english_instructions_text
  ON english_instructions(text COLLATE NOCASE);
